# Generated by Django 2.2.15 on 2023-09-24 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2023, 9, 24, 6, 36, 30, 467418)),
            preserve_default=False,
        ),
    ]
